import type { ScenePreset } from "@/types/scene";

export const scenePresets: ScenePreset[] = [
  {
    id: "studio",
    name: "Studio",
    description: "Clean neutral studio lighting",
    backgroundColor: "#1c1c24",
    ambientIntensity: 0.5,
    ambientColor: "#ffffff",
    keyLightIntensity: 2.0,
    keyLightPosition: [-3, 5, 5],
    keyLightColor: "#ffffff",
    fillLightIntensity: 0.8,
    fillLightPosition: [4, 1, 3],
    fillLightColor: "#ffffff",
    cameraPosition: [0, 0.4, 4.5],
    autoRotate: true,
    autoRotateSpeed: 1.0,
  },
  {
    id: "living-room",
    name: "Living Room",
    description: "Warm cozy ambient lighting",
    backgroundColor: "#2a2018",
    ambientIntensity: 0.35,
    ambientColor: "#ffddaa",
    keyLightIntensity: 1.5,
    keyLightPosition: [2, 3, 4],
    keyLightColor: "#ffe4b5",
    fillLightIntensity: 0.5,
    fillLightPosition: [-2, 1, 5],
    fillLightColor: "#ffcc88",
    cameraPosition: [0, 0.2, 4.0],
    autoRotate: true,
    autoRotateSpeed: 0.7,
  },
  {
    id: "christmas",
    name: "Christmas",
    description: "Festive holiday atmosphere",
    backgroundColor: "#0a0a1a",
    ambientIntensity: 0.25,
    ambientColor: "#4466ff",
    keyLightIntensity: 2.2,
    keyLightPosition: [-3, 4, 5],
    keyLightColor: "#ff6644",
    fillLightIntensity: 0.6,
    fillLightPosition: [3, 2, 4],
    fillLightColor: "#44ff88",
    cameraPosition: [0, 0.4, 4.5],
    autoRotate: true,
    autoRotateSpeed: 1.2,
  },
];
